from groq import Groq 
from config import GROQ_API_KEY, LLM_MODEL 
from prompts.system import FINDLY_SYSTEM_PROMPT, QUERY_REWRITE_PROMPT  

class Generator:  # handles query rewriting and answer generation using the LLM

    def __init__(self):
        self.client = Groq(api_key=GROQ_API_KEY)  # creates a Groq client using the API key

    def rewrite_query(self, query: str) -> list[str]:  # rewrites the user's query into multiple similar queries
        response = self.client.chat.completions.create(  # sends a request to the LLM
            model=LLM_MODEL,  # specifies which LLM to use
            messages=[
                {"role": "user", "content": QUERY_REWRITE_PROMPT.format(query=query)}  # sends the rewrite prompt with the user's query
            ],
            temperature=0.7,  # allows the model to generate slightly different query variations
            max_tokens=150  # limits the response length
        )

        raw = response.choices[0].message.content  # extracts the generated response from the LLM

        lines = [l.strip() for l in raw.strip().split("\n") if l.strip()]  # splits the response into separate lines and removes empty spaces

        queries = [l.split(". ", 1)[-1] if ". " in l else l for l in lines[:3]]  # removes numbering (1., 2., etc.) and keeps only the first 3 queries

        return queries  # returns the rewritten queries as a list

    def generate(self, query: str, context: list[str]) -> str:  # generates the final answer using the retrieved context

        context_text = "\n\n".join(  # combines all retrieved documents into one string
            [f"[{i+1}] {doc}" for i, doc in enumerate(context)]  # adds numbering to each document
        )

        response = self.client.chat.completions.create(  # sends the context and question to the LLM
            model=LLM_MODEL,  # specifies which LLM to use
            messages=[
                {"role": "system", "content": FINDLY_SYSTEM_PROMPT},  # gives the LLM instructions on how to answer
                {"role": "user", "content": f"Context:\n{context_text}\n\nQuestion: {query}"}  # sends the retrieved context and user's question
            ],
            temperature=0.3,  # keeps the response more focused and less random
            max_tokens=300  # limits the maximum answer length
        )

        return response.choices[0].message.content  # returns the final answer generated by the LLM